[TongCreate]
Level=50
LeadLeval=20

[TongTest]
MinMember=1
TimeLong=259200
// ¶à³¤Ê±¼ä¼ì²éÒ»´Î£¬µ¥Î»£ºÃë
ActiveTime=60

[TongScript]
TongScript=\script\tong\tong.lua
MixScript=\script\tong\tong_mix.lua

[InstateCheck]
InstateMasterCheck=0
InstateDirectorCheck=1
InstateManagerCheck=0
InstateMemberCheck=0
InstateRetireCheck=0

// °ï»á»ù½ğ×ª°ï»á¾­Ñé¸÷Ïî²ÎÊı
[MoneyToExp]
// ¶à³¤Ê±¼ä×ªÒ»´Î£¨µ¥Î»£ºÃë£©
TimeLong=750
// °ï»á»ù½ğ»ù±¾Öµ£¬´óÓÚÕâ¸öÖµÕı³£¿ÛÇ®¼Ó¾­Ñé£¬ÉÙÓÚÕâ¸öÖµ¿ÛÇ®¼õ¾­Ñé
MoneyLimit=1000000
// ´ïµ½»ù½ğ»ù±¾Öµ£¬Ã¿´Î¿ÛÇ®»ù±¾Öµ
NormalMoney=5000
// ´ïµ½»ù½ğ»ù±¾Öµ£¬Ã¿´Î¼Ó¾­Ñé»ù±¾Öµ
NormalExp=120
// ´ïµ½»ù½ğ»ù±¾Öµ£¬°ï»áÈËÊı´óÓÚÕâ¸öÊıÒª¶à¿ÛÇ®
NormalMemberLimit=100
// ´ïµ½»ù½ğ»ù±¾Öµ£¬°ï»áÈËÊı³¬¹ıÉÏÃæÕâ¸öÊı£¬Ã¿³¬¹ıÒ»¸öÒª¿Û¶àÉÙÇ®
NormalMemberLimitMoney=50
// Î´´ïµ½»ù½ğ»ù±¾Öµ£¬Ã¿´Î¿ÛÇ®»ù±¾Öµ
LimitMoney=0
// Î´´ïµ½»ù½ğ»ù±¾Öµ£¬Ã¿´Î¿Û¾­Ñé»ù±¾Öµ
LimitExp=0
// ¿¼ÑéÆÚÃ¿´Î¿Û¾­Ñé»ù±¾Öµ
TestExp=0

[DefaultCall]
Master=-[ÙBang chñÙ]
Director=-[ÙTr­ëng L·oÙ]
Director00=-[ÙTr­ëng L·oÙ]
Director01=-[ÙTr­ëng L·oÙ]
Director02=-[ÙTr­ëng L·oÙ]
Director03=-[ÙTr­ëng L·oÙ]
Director04=-[ÙTr­ëng L·oÙ]
Director05=-[ÙTr­ëng L·oÙ]
Director06=-[ÙTr­ëng L·oÙ]
Manager=-[Ù§­êng chñÙ]
Manager00=-[Ù§­êng chñÙ]
Manager01=-[Ù§­êng chñÙ]
Manager02=-[Ù§­êng chñÙ]
Manager03=-[Ù§­êng chñÙ]
Manager04=-[Ù§­êng chñÙ]
Manager05=-[Ù§­êng chñÙ]
Manager06=-[Ù§­êng chñÙ]
Manager07=-[Ù§­êng chñÙ]
Manager08=-[Ù§­êng chñÙ]
Manager09=-[Ù§­êng chñÙ]
Manager10=-[Ù§­êng chñÙ]
Manager11=-[Ù§­êng chñÙ]
Manager12=-[Ù§­êng chñÙ]
Manager13=-[Ù§­êng chñÙ]
Manager14=-[Ù§­êng chñÙ]
Manager15=-[Ù§­êng chñÙ]
Manager16=-[Ù§­êng chñÙ]
Manager17=-[Ù§­êng chñÙ]
Manager18=-[Ù§­êng chñÙ]
Manager19=-[Ù§­êng chñÙ]
Manager20=-[Ù§­êng chñÙ]
Manager21=-[Ù§­êng chñÙ]
Manager22=-[Ù§­êng chñÙ]
Manager23=-[Ù§­êng chñÙ]
Manager24=-[Ù§­êng chñÙ]
Manager25=-[Ù§­êng chñÙ]
Manager26=-[Ù§­êng chñÙ]
Manager27=-[Ù§­êng chñÙ]
Manager28=-[Ù§­êng chñÙ]
Manager29=-[Ù§­êng chñÙ]
Manager30=-[Ù§­êng chñÙ]
Manager31=-[Ù§­êng chñÙ]
Manager32=-[Ù§­êng chñÙ]
Manager33=-[Ù§­êng chñÙ]
Manager34=-[Ù§­êng chñÙ]
Manager35=-[Ù§­êng chñÙ]
Manager36=-[Ù§­êng chñÙ]
Manager37=-[Ù§­êng chñÙ]
Manager38=-[Ù§­êng chñÙ]
Manager39=-[Ù§­êng chñÙ]
Manager40=-[Ù§­êng chñÙ]
Manager41=-[Ù§­êng chñÙ]
Manager42=-[Ù§­êng chñÙ]
Manager43=-[Ù§­êng chñÙ]
Manager44=-[Ù§­êng chñÙ]
Manager45=-[Ù§­êng chñÙ]
Manager46=-[Ù§­êng chñÙ]
Manager47=-[Ù§­êng chñÙ]
Manager48=-[Ù§­êng chñÙ]
Manager49=-[Ù§­êng chñÙ]
Manager50=-[Ù§­êng chñÙ]
Manager51=-[Ù§­êng chñÙ]
Manager52=-[Ù§­êng chñÙ]
Manager53=-[Ù§­êng chñÙ]
Manager54=-[Ù§­êng chñÙ]
Manager55=-[Ù§­êng chñÙ]
Sex00=-Ù§Ö tö 
Sex01=-Ù§Ö tö 
Normal=-Ù§Ö tö 
Retire=-ÙÈn süÙ

[LevelExp]
//µÈ¼¶´ÓµÚ0¼¶¿ªÊ¼
//MaxLevel±ØĞëĞ¡ÓÚ255
MaxLevel=100
1=1
2=2
3=3
4=4
5=5
6=6
7=7
8=8
9=9
10=10
11=11
12=12
13=13
14=14
15=15
16=16
17=17
18=18
19=19
20=20
21=21
22=22
23=23
24=24
25=25
26=26
27=27
28=28
29=29
30=30
31=31
32=32
33=33
34=34
35=35
36=36
37=37
38=38
39=39
40=40
41=41
42=42
43=43
44=44
45=45
46=46
47=47
48=48
49=49
50=50
51=51
52=52
53=53
54=54
55=55
56=56
57=57
58=58
59=59
60=60
61=61
62=62
63=63
64=64
65=65
66=66
67=67
68=68
69=69
70=70
71=71
72=72
73=73
74=74
75=75
76=76
77=77
78=78
79=79
80=80
81=81
82=82
83=83
84=84
85=85
86=86
87=87
88=88
89=89
90=90
91=91
92=92
93=93
94=94
95=95
96=96
97=97
98=98
99=99
100=100

[LevelUnionNum]
0=3
1=3
2=3
3=3
4=3
5=3
6=3
7=3
8=3
9=3
10=4
11=4
12=4
13=4
14=4
15=4
16=4
17=4
18=4
19=4
20=4
21=4
22=4
23=4
24=4
25=4
26=4
27=4
28=4
29=4
30=5
31=5
32=5
33=5
34=5
35=5
36=5
37=5
38=5
39=5
40=5
41=5
42=5
43=5
44=5
45=5
46=5
47=5
48=5
49=5
50=6
51=6
52=6
53=6
54=6
55=6
56=6
57=6
58=6
59=6
60=6
61=6
62=6
63=6
64=6
65=6
66=6
67=6
68=6
69=6
70=7
71=7
72=7
73=7
74=7
75=7
76=7
77=7
78=7
79=7
80=7
81=7
82=7
83=7
84=7
85=7
86=7
87=7
88=7
89=7
90=8
91=8
92=8
93=8
94=8
95=8
96=8
97=8
98=8
99=8
100=8

[Debug]
; °ï»áÔØÈëÊ±ÏÔÊ¾µ÷ÊÔĞÅÏ¢
; 0¡¢Ö»ÏÔÊ¾¼ÆÊı£»1¡¢°ï»á£»2¡¢°ï»á¡¢×÷·»£»3¡¢°ï»á¡¢×÷·»¡¢ÁªÃË£»4¡¢°ï»á¡¢×÷·»¡¢ÁªÃË¡¢³ÉÔ±
DebugOutOnLoad=0
